proc/gdbserial: Use the active xcode-select path instead of a hardcoded Xcode path
go-delve/delve pull request #2229
Opened 2020-11-16 13:43 UTC by aaronsky

Calculate a possible debugserver path in the Xcode.app command line tools using xcode-select instead of a hardcoded path. The path is cached in the same manner as the existing implementation for continued use. 

Fixes #2227

2020-11-16 13:48 UTC, aaronsky commented
I tried to comply with the commit message guidelines in my PR description to make up for me overlooking them in the actual commit. Sorry!

2020-11-16 17:06 UTC, derekparker requested changes
Minor refactor, overall looks good.

A side note, defining a lambda that's immediately called in order to populate a slice member during program initialization is blowing my mind a bit.

2020-11-16 17:06 UTC, derekparker commented on pkg/proc/gdbserial/gdbserver.go
> +		cmd := exec.Command("xcode-select", "--print-path")
This can be cleaned up by refactoring to:

```go
stdout, err := exec.Command(...).Output()
```

2020-11-16 19:18 UTC, aaronsky commented
@derekparker Do you know what could be causing these CI failures? I'm not familiar enough with the rest of Delve to discern the root cause, beyond assuming it's related to my changes.

2020-11-16 21:49 UTC, derekparker commented
@aaronsky can you try rebasing on master and pushing to your branch again? There's a few PRs which have just landed today which clear up some recent test flakyness we've been noticing with the latest 1.15.x builds.

2020-11-16 23:51 UTC, aaronsky commented
Looks like that helped. Thanks!

2020-11-17 14:39 UTC, aarzilli approved these changes
LGTM

2020-11-17 16:49 UTC, derekparker approved these changes

2020-11-17 16:49 UTC, merged