dwarf/frame,proc: use eh_frame section
go-delve/delve pull request #2344
Opened 2021-02-17 09:54 UTC by aarzilli

The eh_frame section is similar to debug_frame but uses a slightly
different format. Gcc and clang by default only emit eh_frame.

2021-03-03 20:02 UTC, derekparker requested changes
A few nits and questions.

2021-03-04 15:59 UTC, aarzilli reviewed
Also didn't get picked up automatically by teamcity: https://delve.beta.teamcity.com/viewLog.html?buildId=2691(also it seems we don't have any linux/amd64 builders at the moment).

2021-03-04 15:59 UTC, aarzilli commented on pkg/dwarf/frame/parser.go
> +	ctx.frame.size = ctx.readEncodedPtr(addrSum(ctx.ehFrameAddr+uint64(rstart), reader), reader, ctx.frame.CIE.ptrEncAddr&0x0f)
I've added a small comment but there isn't much to say. It just happens that the size field is encoded like the beginning address field but it's always absolute so the flags portion of ptrEncAddr needs to be cleared. AFAIK this isn't documented anywhere either, you just have to read gdb or gcc source code to find out.

2021-03-04 15:59 UTC, aarzilli commented on pkg/dwarf/frame/parser.go
> +	if ctx.ehFrameAddr > 0 && len(ctx.frame.CIE.Augmentation) > 0 {
Added a method called `parsingEHFrame() bool`

2021-03-04 15:59 UTC, aarzilli commented on pkg/dwarf/frame/parser.go
> +		reader.Seek(int64(n), io.SeekCurrent)
Yes, but this is reading two things, the first one is a ULEB128 size field `n`, the second is the actual augmentation argument block, of `n` bytes. Added a clarifying comment.

2021-03-04 15:59 UTC, aarzilli commented on pkg/dwarf/frame/parser.go
> +			case 'R':
Done.

2021-03-04 19:17 UTC, derekparker commented on pkg/dwarf/frame/parser.go
> +	rstart := ctx.offset()
startOff sgtm.

2021-03-04 19:23 UTC, derekparker commented on pkg/dwarf/frame/parser.go
> +		reader.Seek(int64(n), io.SeekCurrent)
Ack, ok I understand now, thanks.

2021-03-04 19:23 UTC, derekparker approved these changes
LGTM

2021-03-05 04:17 UTC, merged