dap: suppress error popup for failed evaluation request in repl mode
go-delve/delve pull request #2420
Opened 2021-04-07 20:15 UTC by hyangah

It's expected that users enter invalid expressions through DEBUG
CONSOLE. Pop up for every error is not pleasant.

2021-04-07 22:20 UTC, polinasok approved these changes

2021-04-07 22:22 UTC, polinasok commented
Opps, rashed to approved without realizing that tests did not get updated and are now failing.

2021-04-07 22:23 UTC, polinasok reviewed
Please update the failing tests

2021-04-07 22:26 UTC, polinasok requested changes
Check for ExpectVisibleErrorResponse in the unittests.

2021-04-09 02:15 UTC, hyangah commented
Thanks!

2021-04-09 06:09 UTC, polinasok approved these changes

2021-04-09 08:03 UTC, aarzilli approved these changes
LGTM

2021-04-09 08:03 UTC, merged