proc: fix runtimeTypeToDIE setup
go-delve/delve pull request #2486
Opened 2021-05-15 08:50 UTC by aarzilli

The code populating runtimeTypeToDIE was incorrectly adding StaticBase
to the offset. We never noticed because on statically compiled
executables StaticBase is always zero and on PIE and plugins the
fallback code took care of the problem anyway.

A change in Go 1.17 broke the fallback code, making the issue apparent.

This commit fixes the setup of runtimeTypeToDIE and disables the
fallback code for Go 1.17 and later.

This change also fixes a rare failure in TestPluginVariables when PIE
is enabled.

2021-05-15 08:53 UTC, aarzilli commented
Like #2485 this is split from the Go 1.17 support branch because it's a preexisting bug. No test for this, it will be tested when we start testing Go 1.17 since TestPluginVariables would fail systematically when testing PIE (that test can also fail on < 1.17 but it's very rare).

2021-05-17 17:23 UTC, derekparker approved these changes
LGTM

2021-05-17 17:24 UTC, derekparker commented on pkg/proc/types.go
> +	if goversion.ProducerAfterOrEqual(_type.bi.Producer(), 1, 17) {
Could you add a comment here explaining why we no longer need this in >= 1.17 before I merge this, please.

2021-05-17 17:30 UTC, derekparker requested changes
Changing review from approved to request changes based on my last comment.

2021-05-19 06:29 UTC, aarzilli commented
Done.

2021-05-19 17:42 UTC, derekparker approved these changes
LGTM

2021-05-19 17:42 UTC, merged