terminal: improve 'on' command
go-delve/delve pull request #2556
Opened 2021-06-26 14:28 UTC by aarzilli

Adds the ability to edit the list of commands executed after stopping
on a breakpoint, as well as converting a breakpoint into a tracepoint
and vice versa.

Prior to this it was possible to add commands to a breakpoint but
removing commands or changing a breakpoint into a tracepoint, or vice
versa, could only be done by removing and recreating the breakpoint.

2021-07-21 16:08 UTC, derekparker requested changes

2021-07-21 16:08 UTC, derekparker commented on pkg/terminal/command.go
> +			attrs = append(attrs, "%sargs -v", prefix)
Needs `fmt.Sprintf`.

2021-07-21 16:08 UTC, derekparker commented on pkg/terminal/command.go
> +			attrs = append(attrs, "%sargs", prefix)
Needs `fmt.Sprintf`.

2021-07-21 16:08 UTC, derekparker commented on pkg/terminal/command.go
> +			attrs = append(attrs, "%slocals -v", prefix)
Needs `fmt.Sprintf`.

2021-07-21 16:08 UTC, derekparker commented on pkg/terminal/command.go
> +			attrs = append(attrs, "%slocals", prefix)
Needs `fmt.Sprintf`.

2021-07-22 07:13 UTC, aarzilli commented
Done.

2021-07-22 17:16 UTC, derekparker approved these changes
LGTM

2021-07-22 17:16 UTC, merged