service/dap: make next while nexting error more clear
go-delve/delve pull request #2622
Opened 2021-07-26 23:22 UTC by suzmue

To make it more clear that the user can resume the program when they encounter a next while nexting error, make the exception information have instructions for resuming the program. This implements the suggestions outlined by @polinasok in https://github.com/go-delve/delve/pull/2443#issuecomment-869455021.

<img width="1699" alt="Screen Shot 2021-07-26 at 5 20 28 PM" src="https://user-images.githubusercontent.com/6634754/127071344-72cdb2ff-56a4-4984-9942-52355f956964.png">

2021-07-27 13:50 UTC, aarzilli approved these changes

2021-07-27 16:29 UTC, derekparker approved these changes
LGTM

2021-07-28 07:10 UTC, polinasok requested changes

2021-07-28 07:10 UTC, polinasok commented on service/dap/server.go
> +const BetterNextWhileNextingError = "Step was interrupted by a breakpoint, cannot issue another step request. Use `Continue` to resume the program."
Suggest slightly different wording and formatting with multiple lines:
```
`Unable to step while the previous step is interrupted by a breakpoint.
Use `Continue` to resume the original step command.`
```

2021-07-28 17:15 UTC, polinasok approved these changes
This looks good.
Do you think we should also print a message to the console when the breakpoint is hit that step was interrupted and that Continue can be used to resume, so people see this before they get an exception? I guess we don't keep track of which operation was interrupted, so this might not be straightforward.

2021-07-29 16:57 UTC, suzmue commented
> Do you think we should also print a message to the console when the breakpoint is hit that step was interrupted and that Continue can be used to resume, so people see this before they get an exception? I guess we don't keep track of which operation was interrupted, so this might not be straightforward.

Added a message when the step is interrupted by a breakpoint (state.NextInProgress is true when this is the case).

2021-07-29 17:27 UTC, merged