service/dap: log goroutine id and include source info
go-delve/delve pull request #2730
Opened 2021-10-01 17:49 UTC by suzmue

Log the goroutine id that hit the log message and include the source information. This source information is displayed to the right of the log message and VS Code links it to the appropriate source location.

Updates golang/vscode-go#123

<img width="496" alt="Screen Shot 2021-10-01 at 12 46 34 PM" src="https://user-images.githubusercontent.com/6634754/135664822-77d50102-bca8-472a-bea3-0a82a456bc80.png">

2021-10-02 13:12 UTC, aarzilli approved these changes
LGTM

2021-10-04 16:09 UTC, derekparker approved these changes
LGTM

2021-10-05 16:14 UTC, polinasok requested changes

2021-10-05 18:11 UTC, suzmue commented
<img width="1106" alt="Screen Shot 2021-10-05 at 2 08 19 PM" src="https://user-images.githubusercontent.com/6634754/136078780-07ee1115-cd3d-471b-9c59-300b2c932c23.png">

2021-10-05 18:22 UTC, suzmue commented on service/dap/server.go
> +				Output:   fmt.Sprintf("> goroutine=%d: %s\n", goid, msg),
Done.

2021-10-06 01:28 UTC, polinasok approved these changes

2021-10-06 01:29 UTC, merged