service/dap: fix closing closed channel bug
go-delve/delve pull request #2764
Opened 2021-10-28 19:26 UTC by suzmue

Our previous implementation of waiting on resumeRequestLoop was not
safe, because the channel may be closed several times. This change
removes this bug by instead having two channels to track the two
conditions that we are managing, whether the command has started running
and whether the command has completed (on error or other).

Fixes go-delve/delve#2757

2021-10-30 10:16 UTC, aarzilli approved these changes

2021-11-01 09:32 UTC, polinasok requested changes
I believe we have the following cases when calling async handlers:
1. Debugger command is never called
- there was an error in dap layer set up
- the dap layer determined that it was not necessary to call the command (e.g. stopOnEntry)
- Before: command caller closed setup-done because debugger was never called
2. Debugger command is called, but fails
- Failed during setup
- Failed after successful set-up during execution
- Before: command caller closed setup-done when debugger forgot to (some corner case that might have gotten fixed now) or detected it as closed after it was closed by the debugger. 
3. Debugger command is called and succeeds
- Before: Debugger closed the channel and caller detected it as closed.

All closures occurred on the same goroutine, so select worked.

So what changed? The auto-resume logic added signal redirection with an additional goroutine, so now we could have the new goroutine close the channel when Command signaled setup completion and the per-request goroutine close the same channel at the same time when Command quickly returned? Do I have that right?

So this change separates the two types of done - done setting up inside of the command and done calling (or attempting to call) the command?

2021-11-01 17:30 UTC, suzmue commented
> So what changed? The auto-resume logic added signal redirection with an additional goroutine, so now we could have the new goroutine close the channel when Command signaled setup completion and the per-request goroutine close the same channel at the same time when Command quickly returned? Do I have that right?

Yes this does happen because of the auto resume logic. Since we are adding a separate goroutine to wait for resumeNotify, when we actually call s.debugger.Command, the original goroutine and that other goroutine could try to close the channel at the same time.

2021-11-01 19:09 UTC, polinasok commented
> > So what changed? The auto-resume logic added signal redirection with an additional goroutine, so now we could have the new goroutine close the channel when Command signaled setup completion and the per-request goroutine close the same channel at the same time when Command quickly returned? Do I have that right?
> 
> Yes this does happen because of the auto resume logic. Since we are adding a separate goroutine to wait for resumeNotify, when we actually call s.debugger.Command, the original goroutine and that other goroutine could try to close the channel at the same time.

The channel that is closed on two different goroutines is allowNextStateChange. At one point we had a discussion that with the introduction of changeStateMu we might not need to block the request loop on allowNextStateChange at all. Have you considered that approach instead of adding another channel?

2022-01-27 21:19 UTC, derekparker commented
Just curious on the status of this @polinasok @suzmue.

2022-02-22 17:58 UTC, derekparker commented
Should this PR still be considered for the next release?

2022-02-23 01:14 UTC, suzmue commented
@derekparker I haven't looked at this in a bit, so I will go ahead and rebase it.

I'm not sure it is a high priority that we need to get it in asap. I don't think we have seen any reports of users actually encountering this bug, so I think it is ok to push it to the next release so @polinasok can come back and review

2022-05-03 17:37 UTC, derekparker commented
@suzmue this still needs a rebase. Would we still like to try targeting this for 1.8.4?

2022-05-04 20:21 UTC, suzmue commented
@derekparker Thanks for bumping this. I rebased the change, but need to take a little bit of time to get the context back on this change to address the remaining comments. Will do this by the end of the week.

2022-05-05 20:28 UTC, suzmue commented on service/dap/server.go
> +	defer close(asyncSetupDone.doneCh)
Done.

2022-05-05 20:28 UTC, suzmue commented on service/dap/server.go
> +		// that the setup is done and unlock s.changeStateMu.
Done.

2022-05-05 20:28 UTC, suzmue commented on service/dap/server.go
> +			if allowNextStateChange != nil {
Done.

Yeah this isn't the most readable, even with this changes. hopefully the changes for handling logpoints could make this logic less complicated.

2022-08-11 16:36 UTC, polinasok commented
We just hit this [again](https://delve.teamcity.com/buildConfiguration/Delve_AggregatorBuild/37670?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandPull+Request+Details=true&expandBuildTestsSection=true). I will take a look shortly.

2022-11-11 16:54 UTC, derekparker commented
@suzmue @polinasok is this change still active or should I close it out?

2022-11-16 17:40 UTC, closed without merging